In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("raw_data/daily_20241108T0927_000.csv", skiprows=1, parse_dates=['Date'], date_format="%Y/%m/%d") 
# keep only the rows with valid value for column "Value"
df1 = df1[df1['Value'].notnull()]
# keep only the date part of our datetime object
df1['Date'] = df1['Date'].dt.date

print(type(df1['Date'][0]))
print("Start date: ", df1['Date'].min())
print("End date: ", df1['Date'].max())

<class 'datetime.date'>
Start date:  1911-01-28
End date:  2023-12-31

In [3]:
df1

             ID  PARAM        Date    Value  SYM
0       08LD001      1  1911-01-28    3.820  NaN
154     08LD001      1  1911-07-01  159.000  NaN
155     08LD001      1  1911-07-02  159.000  NaN
156     08LD001      1  1911-07-03  167.000  NaN
157     08LD001      1  1911-07-04  176.000  NaN
...         ...    ...         ...      ...  ...
615613  08LB038      2  2023-12-27    0.804  NaN
615614  08LB038      2  2023-12-28    0.729  NaN
615615  08LB038      2  2023-12-29    0.710  NaN
615616  08LB038      2  2023-12-30    0.706  NaN
615617  08LB038      2  2023-12-31    0.720  NaN

[514188 rows x 5 columns]

In [4]:
df2 = pd.read_csv("raw_data/daily_20241108T0928_001.csv", skiprows=1, parse_dates=['Date'], date_format="%Y/%m/%d") 
# keep only the rows with valid value for column "Value"
df2 = df2[df2['Value'].notnull()]
# keep only the date part of our datetime object
df2['Date'] = df2['Date'].dt.date

print(type(df2['Date'][0]))
print("Start date: ", df2['Date'].min())
print("End date: ", df2['Date'].max())

<class 'datetime.date'>
Start date:  1911-11-01
End date:  2023-12-31

In [5]:
print(len(df1))
print(len(df2))
print(len(joined_df))
joined_df.to_csv("test.csv")

514188
437088

NameError: name 'joined_df' is not defined

In [6]:
# split our data into two sets, one with PARAM == 1 and another with PARAM == 2
df1_1 = df1[df1['PARAM'] == 1]
df1_2 = df1[df1['PARAM'] == 2]
df2_1 = df2[df2['PARAM'] == 1]
df2_2 = df2[df2['PARAM'] == 2]
joined = df1_1.merge(df2_1, on="Date")
print(len(df1_1), len(df2_1), len(joined))
print(f'{len(df1_1)} + {len(df2_1)} = {len(df1_1) + len(df2_1)}')
print("Start date: ", df1_1['Date'].min())
print("End date: ", df1_1['Date'].max())
print("Start date: ", df2_1['Date'].min())
print("End date: ", df2_1['Date'].max())
print("Start date: ", joined['Date'].min())
print("End date: ", joined['Date'].max())

422772 354988 5343479
422772 + 354988 = 777760
Start date:  1911-01-28
End date:  2023-12-31
Start date:  1911-11-01
End date:  2023-12-31
Start date:  1911-11-01
End date:  2023-12-31

In [ ]:
df1_1.nunique()

 ID         20
PARAM        1
Date     39966
Value     3397
SYM          3
dtype: int64

In [ ]:
df2_1.nunique()

 ID         20
PARAM        1
Date     40903
Value     3540
SYM          3
dtype: int64

In [ ]:
joined.nunique()

 ID_x         20
PARAM_x        1
Date       39854
Value_x     3397
SYM_x          3
 ID_y         20
PARAM_y        1
Value_y     3540
SYM_y          3
dtype: int64

In [ ]:
joined.to_csv("test.csv")

### What do I want my df to look like after I'm finished cleaning it up?
| Date | StationID | Value | SYM |

However, I want Dates where I have data available for all Stations.
Can we just do a join on all of our dataframes and up with the intersection of all of our sets of date values?

In [ ]:
# try doing a pivot, to see if we can get dates as the index, and each stationID is a column, their intersection is the value.

df1_1

             ID  PARAM        Date   Value  SYM
0       08LD001      1  1911-01-28    3.82  NaN
154     08LD001      1  1911-07-01  159.00  NaN
155     08LD001      1  1911-07-02  159.00  NaN
156     08LD001      1  1911-07-03  167.00  NaN
157     08LD001      1  1911-07-04  176.00  NaN
...         ...    ...         ...     ...  ...
610865  08LB038      1  2023-12-27    2.70    B
610866  08LB038      1  2023-12-28    2.26    B
610867  08LB038      1  2023-12-29    2.08  NaN
610868  08LB038      1  2023-12-30    2.02  NaN
610869  08LB038      1  2023-12-31    2.26  NaN

[422772 rows x 5 columns]

In [14]:

# df1 = pd.read_csv("raw_data/daily_20241108T0927_000.csv", skiprows=1, parse_dates=['Date'], date_format="%Y/%m/%d") 
df1 = pd.read_csv("raw_data/daily_20241108T0927_000.csv", skiprows=1) 
# keep only the rows with valid value for column "Value"
df1 = df1[df1['Value'].notnull()]
# keep only the date part of our datetime object
# df1['Date'] = df1['Date'].dt.date
df1_1 = df1[df1['PARAM'] == 1]

pivot = df1_1.pivot(columns=" ID", index="Date")
# print(type(pivot.index[0]))
# datetime = pd.to_datetime('1911-01-28', format='%Y-%m-%d').date()
# print(type(datetime))
# print(pivot.loc['2023/12/31'])
# remove any columns that are completely empty, this is can happen since we filtered for datasets with "Flow and Level" data
# However, we then split our datasets into one set with the 'Flow' values, and another with the 'Level' values.
# Unfortunately, these values aren't always available at the same time for a given station. So when we do the pivot and set the
# index to be all possible dates in our dataset, we have a column(s) of all null
# pivot.dropna(how='all', axis=1, inplace=True)
# now lets drop all the remaining rows that still have some NaN values (partially filled columns
# keep rows that have at least 19 columns without NaN as a value
# pivot.dropna(axis=0, thresh=19,inplace=True)
pivot

             PARAM                                                          \
 ID        07FC001 08DB013 08EC001 08EC013 08FB006 08FB011 08HA016 08KE016
Date
1911/01/28     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1911/07/01     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1911/07/02     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1911/07/03     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1911/07/04     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
...            ...     ...     ...     ...     ...     ...     ...     ...
2023/12/27     1.0     1.0     NaN     1.0     1.0     1.0     1.0     1.0
2023/12/28     1.0     1.0     NaN     1.0     1.0     1.0     1.0     1.0
2023/12/29     1.0     1.0     NaN     1.0     1.0     1.0     1.0     1.0
2023/12/30     1.0     1.0     NaN     1.0     1.0     1.0     1.0     1.0
2023/12/31     1.0     1.0     NaN     1.0     1.0     1.0     1.0     1.0

                            ...     SYM                                  \
 ID        08LB020 08LB038  ... 08LB069 08LD001 08MH005 08NB012 08NE008
Date                        ...
1911/01/28     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
1911/07/01     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
1911/07/02     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
1911/07/03     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
1911/07/04     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN
...            ...     ...  ...     ...     ...     ...     ...     ...
2023/12/27     1.0     1.0  ...     NaN     NaN     NaN       B     NaN
2023/12/28     1.0     1.0  ...     NaN     NaN     NaN       B     NaN
2023/12/29     1.0     1.0  ...     NaN     NaN     NaN       B     NaN
2023/12/30     1.0     1.0  ...     NaN     NaN     NaN       B     NaN
2023/12/31     1.0     1.0  ...     NaN     NaN     NaN       B     NaN


 ID        08NH084 08NJ130 08NL004 09AA006 10CD005
Date
1911/01/28     NaN     NaN     NaN     NaN     NaN
1911/07/01     NaN     NaN     NaN     NaN     NaN
1911/07/02     NaN     NaN     NaN     NaN     NaN
1911/07/03     NaN     NaN     NaN     NaN     NaN
1911/07/04     NaN     NaN     NaN     NaN     NaN
...            ...     ...     ...     ...     ...
2023/12/27     NaN     NaN     NaN     NaN       B
2023/12/28     NaN     NaN     NaN     NaN       B
2023/12/29     NaN     NaN     NaN     NaN       B
2023/12/30     NaN     NaN     NaN     NaN       B
2023/12/31     NaN     NaN     NaN     NaN       B

[39966 rows x 60 columns]

In [15]:
df1_1

             ID  PARAM        Date   Value  SYM
0       08LD001      1  1911/01/28    3.82  NaN
154     08LD001      1  1911/07/01  159.00  NaN
155     08LD001      1  1911/07/02  159.00  NaN
156     08LD001      1  1911/07/03  167.00  NaN
157     08LD001      1  1911/07/04  176.00  NaN
...         ...    ...         ...     ...  ...
610865  08LB038      1  2023/12/27    2.70    B
610866  08LB038      1  2023/12/28    2.26    B
610867  08LB038      1  2023/12/29    2.08  NaN
610868  08LB038      1  2023/12/30    2.02  NaN
610869  08LB038      1  2023/12/31    2.26  NaN

[422772 rows x 5 columns]

In [8]:
# want my index to be the date
# multi header
#    Date     |----------------------------------|Station ID---------------------------------|
#  2023-12-29 |longitude|latitude|Flow|Height|Precipitation|Temperature|Min/Max of those|etc.|
index = pd.MultiIndex.from_frame(pivot)
print(index)

MultiIndex([(  4.8,  1.44, nan, 46.8, 30.9, 76.2, 0.026,  1.48,  3.3, ...),
            ( 1.78,  0.28, nan, 34.9, 33.6, 88.5, 0.791, 0.837, 3.14, ...),
            (0.949, 0.373, nan, 27.8, 19.2, 44.9,  1.22,  1.08, 2.82, ...),
            (0.698, 0.203, nan, 22.9, 12.3, 28.8, 0.531,  1.85, 2.42, ...),
            ( 0.81, 0.285, nan, 23.1, 12.6, 31.0, 0.958,  1.99, 2.46, ...),
            (0.939, 0.342, nan, 23.4, 12.8, 31.7, 0.894,  2.14, 2.53, ...),
            ( 1.09, 0.297, nan, 23.2, 12.9, 31.3, 0.746,  2.29, 2.63, ...),
            ( 1.26, 0.269, nan, 22.9, 13.0, 30.7, 0.876,  2.28, 2.76, ...),
            ( 1.47, 0.261, nan, 23.1, 13.4, 30.8, 0.712,  2.28, 2.87, ...),
            (  1.7, 0.273, nan, 22.8, 14.0, 33.3, 0.661,  2.29, 2.94, ...),
            ...
            (0.743, 0.376, nan, 10.0, 6.62, 31.6, 0.497,  1.01, 3.07, ...),
            (0.732, 0.312, nan, 9.66, 6.42, 31.6, 0.428,  1.03, 3.02, ...),
            (0.721, 0.301, nan, 9.68, 6.47, 29.2, 0.392,  1.11, 2.93, ...),
            ( 0.71, 0.321, nan, 9.65, 6.55, 28.0, 0.491,  2.11, 2.87, ...),
            (0.699, 0.389, nan, 9.81, 6.75, 33.0,  0.97,  1.25, 2.83, ...),
            (0.689, 0.383, nan, 9.56, 6.74, 33.8, 0.789,  1.01, 2.83, ...),
            (0.678, 0.339, nan, 9.46, 6.75, 31.9, 0.763, 0.998, 2.86, ...),
            (0.667, 0.436, nan, 9.39, 6.78, 30.5, 0.726, 0.987, 2.85, ...),
            (0.656, 0.705, nan, 9.36, 6.78, 29.7, 0.661,  0.97, 2.79, ...),
            (0.645, 0.696, nan, 9.39, 6.71, 29.4, 0.563, 0.946, 2.84, ...)],
           names=['07FC001', '08DB013', '08EC001', '08EC013', '08FB006', '08FB011', '08HA016', '08KE016', '08LB020', '08LB038', '08LB069', '08LD001', '08MH005', '08NB012', '08NE008', '08NH084', '08NJ130', '08NL004', '09AA006', '10CD005'], length=3520)

In [25]:
import csv
data = []
with open("raw_data/daily_20241108T0927_000.csv", newline='') as f:
    reader = csv.reader(f)
    csvFile = list(reader)
    data.append(csvFile)

data

[[['\ufeff\ufeffDaily Discharge (m3/s) (PARAM = 1) and Daily Water Level (m) (PARAM = 2)'],
  [' ID', 'PARAM', 'Date', 'Value', 'SYM'],
  ['08LD001', '1', '1911/01/28', '3.82', ''],
  ['08LD001', '1', '1911/01/29', '', ''],
  ['08LD001', '1', '1911/01/30', '', ''],
  ['08LD001', '1', '1911/01/31', '', ''],
  ['08LD001', '1', '1911/02/01', '', ''],
  ['08LD001', '1', '1911/02/02', '', ''],
  ['08LD001', '1', '1911/02/03', '', ''],
  ['08LD001', '1', '1911/02/04', '', ''],
  ['08LD001', '1', '1911/02/05', '', ''],
  ['08LD001', '1', '1911/02/06', '', ''],
  ['08LD001', '1', '1911/02/07', '', ''],
  ['08LD001', '1', '1911/02/08', '', ''],
  ['08LD001', '1', '1911/02/09', '', ''],
  ['08LD001', '1', '1911/02/10', '', ''],
  ['08LD001', '1', '1911/02/11', '', ''],
  ['08LD001', '1', '1911/02/12', '', ''],
  ['08LD001', '1', '1911/02/13', '', ''],
  ['08LD001', '1', '1911/02/14', '', ''],
  ['08LD001', '1', '1911/02/15', '', ''],
  ['08LD001', '1', '1911/02/16', '', ''],
  ['08LD001', '1', '1911/02/17', '', ''],
  ['08LD001', '1', '1911/02/18', '', ''],
  ['08LD001', '1', '1911/02/19', '', ''],
  ['08LD001', '1', '1911/02/20', '', ''],
  ['08LD001', '1', '1911/02/21', '', ''],
  ['08LD001', '1', '1911/02/22', '', ''],
  ['08LD001', '1', '1911/02/23', '', ''],
  ['08LD001', '1', '1911/02/24', '', ''],
  ['08LD001', '1', '1911/02/25', '', ''],
  ['08LD001', '1', '1911/02/26', '', ''],
  ['08LD001', '1', '1911/02/27', '', ''],
  ['08LD001', '1', '1911/02/28', '', ''],
  ['08LD001', '1', '1911/03/01', '', ''],
  ['08LD001', '1', '1911/03/02', '', ''],
  ['08LD001', '1', '1911/03/03', '', ''],
  ['08LD001', '1', '1911/03/04', '', ''],
  ['08LD001', '1', '1911/03/05', '', ''],
  ['08LD001', '1', '1911/03/06', '', ''],
  ['08LD001', '1', '1911/03/07', '', ''],
  ['08LD001', '1', '1911/03/08', '', ''],
  ['08LD001', '1', '1911/03/09', '', ''],
  ['08LD001', '1', '1911/03/10', '', ''],
  ['08LD001', '1', '1911/03/11', '', ''],
  ['08LD001', '1', '1911/03/12', '', ''],
  ['08LD001', '1', '1911/03/13', '', ''],
  ['08LD001', '1', '1911/03/14', '', ''],
  ['08LD001', '1', '1911/03/15', '', ''],
  ['08LD001', '1', '1911/03/16', '', ''],
  ['08LD001', '1', '1911/03/17', '', ''],
  ['08LD001', '1', '1911/03/18', '', ''],
  ['08LD001', '1', '1911/03/19', '', ''],
  ['08LD001', '1', '1911/03/20', '', ''],
  ['08LD001', '1', '1911/03/21', '', ''],
  ['08LD001', '1', '1911/03/22', '', ''],
  ['08LD001', '1', '1911/03/23', '', ''],
  ['08LD001', '1', '1911/03/24', '', ''],
  ['08LD001', '1', '1911/03/25', '', ''],
  ['08LD001', '1', '1911/03/26', '', ''],
  ['08LD001', '1', '1911/03/27', '', ''],
  ['08LD001', '1', '1911/03/28', '', ''],
  ['08LD001', '1', '1911/03/29', '', ''],
  ['08LD001', '1', '1911/03/30', '', ''],
  ['08LD001', '1', '1911/03/31', '', ''],
  ['08LD001', '1', '1911/04/01', '', ''],
  ['08LD001', '1', '1911/04/02', '', ''],
  ['08LD001', '1', '1911/04/03', '', ''],
  ['08LD001', '1', '1911/04/04', '', ''],
  ['08LD001', '1', '1911/04/05', '', ''],
  ['08LD001', '1', '1911/04/06', '', ''],
  ['08LD001', '1', '1911/04/07', '', ''],
  ['08LD001', '1', '1911/04/08', '', ''],
  ['08LD001', '1', '1911/04/09', '', ''],
  ['08LD001', '1', '1911/04/10', '', ''],
  ['08LD001', '1', '1911/04/11', '', ''],
  ['08LD001', '1', '1911/04/12', '', ''],
  ['08LD001', '1', '1911/04/13', '', ''],
  ['08LD001', '1', '1911/04/14', '', ''],
  ['08LD001', '1', '1911/04/15', '', ''],
  ['08LD001', '1', '1911/04/16', '', ''],
  ['08LD001', '1', '1911/04/17', '', ''],
  ['08LD001', '1', '1911/04/18', '', ''],
  ['08LD001', '1', '1911/04/19', '', ''],
  ['08LD001', '1', '1911/04/20', '', ''],
  ['08LD001', '1', '1911/04/21', '', ''],
  ['08LD001', '1', '1911/04/22', '', ''],
  ['08LD001', '1', '1911/04/23', '', ''],
  ['08LD001', '1', '1911/04/24', '', ''],
  ['08LD001', '1', '1911/04/25', '', ''],
  ['08LD001', '1', '1911/04/26', '', ''],
  ['08LD001', '1', '1911/04/27', '', ''],
  ['08LD001', '1', '1911/04/28', '', ''],
  ['08LD001', '1', '1911/04/29', '', ''],
  ['08LD001', '1', '1911/04/30', '', ''],
  ['08LD001', '1', '1911/05/01', '', ''],
  ['08LD001', '1', '1911/05/02', '', ''],
  ['08LD001', '1', '1911/05/03', '', ''],
  ['08LD001', '1', '1911/05/04', '', ''],
  ['08LD001', '1', '1911/05/05', '', ''],
  ['08LD001', '1', '1911/05/06', '', ''],
  ['08LD001', '1', '1911/05/07', '', ''],
  ['08LD001', '1', '1911/05/08', '', ''],
  ['08LD001', '1', '1911/05/09', '', ''],
  ['08LD001', '1', '1911/05/10', '', ''],
  ['08LD001', '1', '1911/05/11', '', ''],
  ['08LD001', '1', '1911/05/12', '', ''],
  ['08LD001', '1', '1911/05/13', '', ''],
  ['08LD001', '1', '1911/05/14', '', ''],
  ['08LD001', '1', '1911/05/15', '', ''],
  ['08LD001', '1', '1911/05/16', '', ''],
  ['08LD001', '1', '1911/05/17', '', ''],
  ['08LD001', '1', '1911/05/18', '', ''],
  ['08LD001', '1', '1911/05/19', '', ''],
  ['08LD001', '1', '1911/05/20', '', ''],
  ['08LD001', '1', '1911/05/21', '', ''],
  ['08LD001', '1', '1911/05/22', '', ''],
  ['08LD001', '1', '1911/05/23', '', ''],
  ['08LD001', '1', '1911/05/24', '', ''],
  ['08LD001', '1', '1911/05/25', '', ''],
  ['08LD001', '1', '1911/05/26', '', ''],
  ['08LD001', '1', '1911/05/27', '', ''],
  ['08LD001', '1', '1911/05/28', '', ''],
  ['08LD001', '1', '1911/05/29', '', ''],
  ['08LD001', '1', '1911/05/30', '', ''],
  ['08LD001', '1', '1911/05/31', '', ''],
  ['08LD001', '1', '1911/06/01', '', ''],
  ['08LD001', '1', '1911/06/02', '', ''],
  ['08LD001', '1', '1911/06/03', '', ''],
  ['08LD001', '1', '1911/06/04', '', ''],
  ['08LD001', '1', '1911/06/05', '', ''],
  ['08LD001', '1', '1911/06/06', '', ''],
  ['08LD001', '1', '1911/06/07', '', ''],
  ['08LD001', '1', '1911/06/08', '', ''],
  ['08LD001', '1', '1911/06/09', '', ''],
  ['08LD001', '1', '1911/06/10', '', ''],
  ['08LD001', '1', '1911/06/11', '', ''],
  ['08LD001', '1', '1911/06/12', '', ''],
  ['08LD001', '1', '1911/06/13', '', ''],
  ['08LD001', '1', '1911/06/14', '', ''],
  ['08LD001', '1', '1911/06/15', '', ''],
  ['08LD001', '1', '1911/06/16', '', ''],
  ['08LD001', '1', '1911/06/17', '', ''],
  ['08LD001', '1', '1911/06/18', '', ''],
  ['08LD001', '1', '1911/06/19', '', ''],
  ['08LD001', '1', '1911/06/20', '', ''],
  ['08LD001', '1', '1911/06/21', '', ''],
  ['08LD001', '1', '1911/06/22', '', ''],
  ['08LD001', '1', '1911/06/23', '', ''],
  ['08LD001', '1', '1911/06/24', '', ''],
  ['08LD001', '1', '1911/06/25', '', ''],
  ['08LD001', '1', '1911/06/26', '', ''],
  ['08LD001', '1', '1911/06/27', '', ''],
  ['08LD001', '1', '1911/06/28', '', ''],
  ['08LD001', '1', '1911/06/29', '', ''],
  ['08LD001', '1', '1911/06/30', '', ''],
  ['08LD001', '1', '1911/07/01', '159', ''],
  ['08LD001', '1', '1911/07/02', '159', ''],
  ['08LD001', '1', '1911/07/03', '167', ''],
  ['08LD001', '1', '1911/07/04', '176', ''],
  ['08LD001', '1', '1911/07/05', '167', ''],
  ['08LD001', '1', '1911/07/06', '167', ''],
  ['08LD001', '1', '1911/07/07', '167', ''],
  ['08LD001', '1', '1911/07/08', '167', ''],
  ['08LD001', '1', '1911/07/09', '176', ''],
  ['08LD001', '1', '1911/07/10', '184', ''],
  ['08LD001', '1', '1911/07/11', '159', ''],
  ['08LD001', '1', '1911/07/12', '159', ''],
  ['08LD001', '1', '1911/07/13', '142', ''],
  ['08LD001', '1', '1911/07/14', '127', ''],
  ['08LD001', '1', '1911/07/15', '127', ''],
  ['08LD001', '1', '1911/07/16', '184', ''],
  ['08LD001', '1', '1911/07/17', '184', ''],
  ['08LD001', '1', '1911/07/18', '184', ''],
  ['08LD001', '1', '1911/07/19', '151', ''],
  ['08LD001', '1', '1911/07/20', '142', ''],
  ['08LD001', '1', '1911/07/21', '119', ''],
  ['08LD001', '1', '1911/07/22', '106', ''],
  ['08LD001', '1', '1911/07/23', '106', ''],
  ['08LD001', '1', '1911/07/24', '92.9', ''],
  ['08LD001', '1', '1911/07/25', '106', ''],
  ['08LD001', '1', '1911/07/26', '99.1', ''],
  ['08LD001', '1', '1911/07/27', '106', ''],
  ['08LD001', '1', '1911/07/28', '99.1', ''],
  ['08LD001', '1', '1911/07/29', '99.1', ''],
  ['08LD001', '1', '1911/07/30', '86.9', ''],
  ['08LD001', '1', '1911/07/31', '112', ''],
  ['08LD001', '1', '1911/08/01', '81.3', ''],
  ['08LD001', '1', '1911/08/02', '81.3', ''],
  ['08LD001', '1', '1911/08/03', '81.3', ''],
  ['08LD001', '1', '1911/08/04', '81.3', ''],
  ['08LD001', '1', '1911/08/05', '81.3', ''],
  ['08LD001', '1', '1911/08/06', '81.3', ''],
  ['08LD001', '1', '1911/08/07', '81.3', ''],
  ['08LD001', '1', '1911/08/08', '81.3', ''],
  ['08LD001', '1', '1911/08/09', '81.3', ''],
  ['08LD001', '1', '1911/08/10', '', ''],
  ['08LD001', '1', '1911/08/11', '', ''],
  ['08LD001', '1', '1911/08/12', '', ''],
  ['08LD001', '1', '1911/08/13', '', ''],
  ['08LD001', '1', '1911/08/14', '', ''],
  ['08LD001', '1', '1911/08/15', '', ''],
  ['08LD001', '1', '1911/08/16', '', ''],
  ['08LD001', '1', '1911/08/17', '', ''],
  ['08LD001', '1', '1911/08/18', '', ''],
  ['08LD001', '1', '1911/08/19', '', ''],
  ['08LD001', '1', '1911/08/20', '', ''],
  ['08LD001', '1', '1911/08/21', '', ''],
  ['08LD001', '1', '1911/08/22', '', ''],
  ['08LD001', '1', '1911/08/23', '', ''],
  ['08LD001', '1', '1911/08/24', '', ''],
  ['08LD001', '1', '1911/08/25', '', ''],
  ['08LD001', '1', '1911/08/26', '', ''],
  ['08LD001', '1', '1911/08/27', '', ''],
  ['08LD001', '1', '1911/08/28', '', ''],
  ['08LD001', '1', '1911/08/29', '', ''],
  ['08LD001', '1', '1911/08/30', '', ''],
  ['08LD001', '1', '1911/08/31', '', ''],
  ['08LD001', '1', '1911/09/01', '', ''],
  ['08LD001', '1', '1911/09/02', '', ''],
  ['08LD001', '1', '1911/09/03', '', ''],
  ['08LD001', '1', '1911/09/04', '', ''],
  ['08LD001', '1', '1911/09/05', '', ''],
  ['08LD001', '1', '1911/09/06', '', ''],
  ['08LD001', '1', '1911/09/07', '', ''],
  ['08LD001', '1', '1911/09/08', '', ''],
  ['08LD001', '1', '1911/09/09', '', ''],
  ['08LD001', '1', '1911/09/10', '', ''],
  ['08LD001', '1', '1911/09/11', '', ''],
  ['08LD001', '1', '1911/09/12', '', ''],
  ['08LD001', '1', '1911/09/13', '', ''],
  ['08LD001', '1', '1911/09/14', '', ''],
  ['08LD001', '1', '1911/09/15', '', ''],
  ['08LD001', '1', '1911/09/16', '', ''],
  ['08LD001', '1', '1911/09/17', '', ''],
  ['08LD001', '1', '1911/09/18', '', ''],
  ['08LD001', '1', '1911/09/19', '', ''],
  ['08LD001', '1', '1911/09/20', '', ''],
  ['08LD001', '1', '1911/09/21', '', ''],
  ['08LD001', '1', '1911/09/22', '', ''],
  ['08LD001', '1', '1911/09/23', '', ''],
  ['08LD001', '1', '1911/09/24', '', ''],
  ['08LD001', '1', '1911/09/25', '', ''],
  ['08LD001', '1', '1911/09/26', '', ''],
  ['08LD001', '1', '1911/09/27', '', ''],
  ['08LD001', '1', '1911/09/28', '', ''],
  ['08LD001', '1', '1911/09/29', '', ''],
  ['08LD001', '1', '1911/09/30', '', ''],
  ['08LD001', '1', '1911/10/01', '', ''],
  ['08LD001', '1', '1911/10/02', '', ''],
  ['08LD001', '1', '1911/10/03', '', ''],
  ['08LD001', '1', '1911/10/04', '', ''],
  ['08LD001', '1', '1911/10/05', '', ''],
  ['08LD001', '1', '1911/10/06', '', ''],
  ['08LD001', '1', '1911/10/07', '', ''],
  ['08LD001', '1', '1911/10/08', '', ''],
  ['08LD001', '1', '1911/10/09', '', ''],
  ['08LD001', '1', '1911/10/10', '', ''],
  ['08LD001', '1', '1911/10/11', '', ''],
  ['08LD001', '1', '1911/10/12', '', ''],
  ['08LD001', '1', '1911/10/13', '', ''],
  ['08LD001', '1', '1911/10/14', '', ''],
  ['08LD001', '1', '1911/10/15', '', ''],
  ['08LD001', '1', '1911/10/16', '', ''],
  ['08LD001', '1', '1911/10/17', '', ''],
  ['08LD001', '1', '1911/10/18', '', ''],
  ['08LD001', '1', '1911/10/19', '', ''],
  ['08LD001', '1', '1911/10/20', '', ''],
  ['08LD001', '1', '1911/10/21', '', ''],
  ['08LD001', '1', '1911/10/22', '', ''],
  ['08LD001', '1', '1911/10/23', '', ''],
  ['08LD001', '1', '1911/10/24', '', ''],
  ['08LD001', '1', '1911/10/25', '', ''],
  ['08LD001', '1', '1911/10/26', '', ''],
  ['08LD001', '1', '1911/10/27', '', ''],
  ['08LD001', '1', '1911/10/28', '', ''],
  ['08LD001', '1', '1911/10/29', '', ''],
  ['08LD001', '1', '1911/10/30', '', ''],
  ['08LD001', '1', '1911/10/31', '', ''],
  ['08LD001', '1', '1911/11/01', '', ''],
  ['08LD001', '1', '1911/11/02', '', ''],
  ['08LD001', '1', '1911/11/03', '', ''],
  ['08LD001', '1', '1911/11/04', '', ''],
  ['08LD001', '1', '1911/11/05', '', ''],
  ['08LD001', '1', '1911/11/06', '', ''],
  ['08LD001', '1', '1911/11/07', '', ''],
  ['08LD001', '1', '1911/11/08', '', ''],
  ['08LD001', '1', '1911/11/09', '', ''],
  ['08LD001', '1', '1911/11/10', '', ''],
  ['08LD001', '1', '1911/11/11', '30.0', ''],
  ['08LD001', '1', '1911/11/12', '30.0', ''],
  ['08LD001', '1', '1911/11/13', '30.0', ''],
  ['08LD001', '1', '1911/11/14', '30.0', ''],
  ['08LD001', '1', '1911/11/15', '62.6', ''],
  ['08LD001', '1', '1911/11/16', '71.1', ''],
  ['08LD001', '1', '1911/11/17', '62.6', ''],
  ['08LD001', '1', '1911/11/18', '62.6', ''],
  ['08LD001', '1', '1911/11/19', '58.6', ''],
  ['08LD001', '1', '1911/11/20', '54.9', ''],
  ['08LD001', '1', '1911/11/21', '54.9', ''],
  ['08LD001', '1', '1911/11/22', '51.3', ''],
  ['08LD001', '1', '1911/11/23', '3.82', ''],
  ['08LD001', '1', '1911/11/24', '3.82', ''],
  ['08LD001', '1', '1911/11/25', '3.82', ''],
  ['08LD001', '1', '1911/11/26', '3.82', ''],
  ['08LD001', '1', '1911/11/27', '3.82', ''],
  ['08LD001', '1', '1911/11/28', '3.82', ''],
  ['08LD001', '1', '1911/11/29', '3.82', ''],
  ['08LD001', '1', '1911/11/30', '3.82', ''],
  ['08LD001', '1', '1911/12/01', '3.82', ''],
  ['08LD001', '1', '1911/12/02', '3.82', ''],
  ['08LD001', '1', '1911/12/03', '3.82', ''],
  ['08LD001', '1', '1911/12/04', '3.82', ''],
  ['08LD001', '1', '1911/12/05', '3.82', ''],
  ['08LD001', '1', '1911/12/06', '3.82', ''],
  ['08LD001', '1', '1911/12/07', '3.82', ''],
  ['08LD001', '1', '1911/12/08', '3.82', ''],
  ['08LD001', '1', '1911/12/09', '3.82', ''],
  ['08LD001', '1', '1911/12/10', '3.82', ''],
  ['08LD001', '1', '1911/12/11', '3.82', ''],
  ['08LD001', '1', '1911/12/12', '3.68', ''],
  ['08LD001', '1', '1911/12/13', '3.82', ''],
  ['08LD001', '1', '1911/12/14', '3.82', ''],
  ['08LD001', '1', '1911/12/15', '3.82', ''],
  ['08LD001', '1', '1911/12/16', '3.77', ''],
  ['08LD001', '1', '1911/12/17', '3.77', ''],
  ['08LD001', '1', '1911/12/18', '3.77', ''],
  ['08LD001', '1', '1911/12/19', '3.77', ''],
  ['08LD001', '1', '1911/12/20', '3.77', ''],
  ['08LD001', '1', '1911/12/21', '3.77', ''],
  ['08LD001', '1', '1911/12/22', '3.77', ''],
  ['08LD001', '1', '1911/12/23', '3.77', ''],
  ['08LD001', '1', '1911/12/24', '3.77', ''],
  ['08LD001', '1', '1911/12/25', '3.77', ''],
  ['08LD001', '1', '1911/12/26', '3.77', ''],
  ['08LD001', '1', '1911/12/27', '3.77', ''],
  ['08LD001', '1', '1911/12/28', '3.77', ''],
  ['08LD001', '1', '1911/12/29', '3.82', ''],
  ['08LD001', '1', '1911/12/30', '3.82', ''],
  ['08LD001', '1', '1911/12/31', '3.82', ''],
  ['08LD001', '1', '1912/01/01', '3.82', ''],
  ['08LD001', '1', '1912/01/02', '3.82', ''],
  ['08LD001', '1', '1912/01/03', '3.82', ''],
  ['08LD001', '1', '1912/01/04', '3.82', ''],
  ['08LD001', '1', '1912/01/05', '3.82', ''],
  ['08LD001', '1', '1912/01/06', '3.82', ''],
  ['08LD001', '1', '1912/01/07', '3.82', ''],
  ['08LD001', '1', '1912/01/08', '3.82', ''],
  ['08LD001', '1', '1912/01/09', '3.82', ''],
  ['08LD001', '1', '1912/01/10', '3.82', ''],
  ['08LD001', '1', '1912/01/11', '3.82', ''],
  ['08LD001', '1', '1912/01/12', '3.82', ''],
  ['08LD001', '1', '1912/01/13', '3.82', ''],
  ['08LD001', '1', '1912/01/14', '3.82', ''],
  ['08LD001', '1', '1912/01/15', '3.82', ''],
  ['08LD001', '1', '1912/01/16', '3.82', ''],
  ['08LD001', '1', '1912/01/17', '81.3', ''],
  ['08LD001', '1', '1912/01/18', '81.3', ''],
  ['08LD001', '1', '1912/01/19', '66.5', ''],
  ['08LD001', '1', '1912/01/20', '66.5', ''],
  ['08LD001', '1', '1912/01/21', '62.3', ''],
  ['08LD001', '1', '1912/01/22', '62.3', ''],
  ['08LD001', '1', '1912/01/23', '62.3', ''],
  ['08LD001', '1', '1912/01/24', '58.6', ''],
  ['08LD001', '1', '1912/01/25', '54.7', ''],
  ['08LD001', '1', '1912/01/26', '3.82', ''],
  ['08LD001', '1', '1912/01/27', '3.82', ''],
  ['08LD001', '1', '1912/01/28', '3.82', ''],
  ['08LD001', '1', '1912/01/29', '3.82', ''],
  ['08LD001', '1', '1912/01/30', '3.82', ''],
  ['08LD001', '1', '1912/01/31', '3.60', ''],
  ['08LD001', '1', '1912/02/01', '3.60', ''],
  ['08LD001', '1', '1912/02/02', '3.60', ''],
  ['08LD001', '1', '1912/02/03', '3.60', ''],
  ['08LD001', '1', '1912/02/04', '3.60', ''],
  ['08LD001', '1', '1912/02/05', '3.60', ''],
  ['08LD001', '1', '1912/02/06', '3.60', ''],
  ['08LD001', '1', '1912/02/07', '3.60', ''],
  ['08LD001', '1', '1912/02/08', '3.60', ''],
  ['08LD001', '1', '1912/02/09', '3.60', ''],
  ['08LD001', '1', '1912/02/10', '3.60', ''],
  ['08LD001', '1', '1912/02/11', '3.60', ''],
  ['08LD001', '1', '1912/02/12', '3.60', ''],
  ['08LD001', '1', '1912/02/13', '3.60', ''],
  ['08LD001', '1', '1912/02/14', '3.60', ''],
  ['08LD001', '1', '1912/02/15', '3.60', ''],
  ['08LD001', '1', '1912/02/16', '3.60', ''],
  ['08LD001', '1', '1912/02/17', '3.60', ''],
  ['08LD001', '1', '1912/02/18', '3.60', ''],
  ['08LD001', '1', '1912/02/19', '3.60', ''],
  ['08LD001', '1', '1912/02/20', '32.0', ''],
  ['08LD001', '1', '1912/02/21', '32.0', ''],
  ['08LD001', '1', '1912/02/22', '32.0', ''],
  ['08LD001', '1', '1912/02/23', '44.7', ''],
  ['08LD001', '1', '1912/02/24', '44.7', ''],
  ['08LD001', '1', '1912/02/25', '44.7', ''],
  ['08LD001', '1', '1912/02/26', '44.7', ''],
  ['08LD001', '1', '1912/02/27', '44.7', ''],
  ['08LD001', '1', '1912/02/28', '44.7', ''],
  ['08LD001', '1', '1912/02/29', '42.2', ''],
  ['08LD001', '1', '1912/03/01', '39.1', ''],
  ['08LD001', '1', '1912/03/02', '39.1', ''],
  ['08LD001', '1', '1912/03/03', '39.1', ''],
  ['08LD001', '1', '1912/03/04', '34.3', ''],
  ['08LD001', '1', '1912/03/05', '30.0', ''],
  ['08LD001', '1', '1912/03/06', '30.0', ''],
  ['08LD001', '1', '1912/03/07', '28.2', ''],
  ['08LD001', '1', '1912/03/08', '28.2', ''],
  ['08LD001', '1', '1912/03/09', '28.2', ''],
  ['08LD001', '1', '1912/03/10', '26.3', ''],
  ['08LD001', '1', '1912/03/11', '26.3', ''],
  ['08LD001', '1', '1912/03/12', '24.6', ''],
  ['08LD001', '1', '1912/03/13', '24.6', ''],
  ['08LD001', '1', '1912/03/14', '22.9', ''],
  ['08LD001', '1', '1912/03/15', '22.9', ''],
  ['08LD001', '1', '1912/03/16', '22.9', ''],
  ['08LD001', '1', '1912/03/17', '22.9', ''],
  ['08LD001', '1', '1912/03/18', '21.4', ''],
  ['08LD001', '1', '1912/03/19', '21.4', ''],
  ['08LD001', '1', '1912/03/20', '19.8', ''],
  ['08LD001', '1', '1912/03/21', '19.8', ''],
  ['08LD001', '1', '1912/03/22', '19.8', ''],
  ['08LD001', '1', '1912/03/23', '18.4', ''],
  ['08LD001', '1', '1912/03/24', '18.4', ''],
  ['08LD001', '1', '1912/03/25', '18.4', ''],
  ['08LD001', '1', '1912/03/26', '18.4', ''],
  ['08LD001', '1', '1912/03/27', '17.0', ''],
  ['08LD001', '1', '1912/03/28', '17.0', ''],
  ['08LD001', '1', '1912/03/29', '17.0', ''],
  ['08LD001', '1', '1912/03/30', '17.0', ''],
  ['08LD001', '1', '1912/03/31', '3.11', ''],
  ['08LD001', '1', '1912/04/01', '3.11', ''],
  ['08LD001', '1', '1912/04/02', '3.11', ''],
  ['08LD001', '1', '1912/04/03', '3.11', ''],
  ['08LD001', '1', '1912/04/04', '3.11', ''],
  ['08LD001', '1', '1912/04/05', '3.11', ''],
  ['08LD001', '1', '1912/04/06', '3.11', ''],
  ['08LD001', '1', '1912/04/07', '3.11', ''],
  ['08LD001', '1', '1912/04/08', '3.11', ''],
  ['08LD001', '1', '1912/04/09', '3.11', ''],
  ['08LD001', '1', '1912/04/10', '3.11', ''],
  ['08LD001', '1', '1912/04/11', '3.11', ''],
  ['08LD001', '1', '1912/04/12', '3.11', ''],
  ['08LD001', '1', '1912/04/13', '3.11', ''],
  ['08LD001', '1', '1912/04/14', '3.11', ''],
  ['08LD001', '1', '1912/04/15', '3.11', ''],
  ['08LD001', '1', '1912/04/16', '3.11', ''],
  ['08LD001', '1', '1912/04/17', '3.11', ''],
  ['08LD001', '1', '1912/04/18', '3.11', ''],
  ['08LD001', '1', '1912/04/19', '51.3', ''],
  ['08LD001', '1', '1912/04/20', '51.3', ''],
  ['08LD001', '1', '1912/04/21', '54.7', ''],
  ['08LD001', '1', '1912/04/22', '54.7', ''],
  ['08LD001', '1', '1912/04/23', '58.6', ''],
  ['08LD001', '1', '1912/04/24', '58.6', ''],

In [32]:
import os
import sys
raw_data_path = "raw_data"
clean_data_path = "clean_data"
if not os.path.isdir(clean_data_path):
    os.makedirs(clean_data_path)
# data = pd.DataFrame()
# # TODO specify a schema so that we dont get a DtypeWawrning of columns having mixed types
# for filename in os.listdir(raw_data_path):
#     print(filename)
#     df = pd.read_csv(f'raw_data/{filename}', skiprows=1)
#     df = df[df['Value'].notnull()]
#     print(f'Input file {filename} has {len(df)} non-null elements.')
#     # df_new.to_csv(f'{clean_data_path}/{filename}')

data = []
for filename in os.listdir(raw_data_path):
    with open(f'{raw_data_path}\\{filename}', newline='') as f:
        reader = list(csv.reader(f))
        print(f'Input file {filename} has {len(list(reader))} non-null elements.')
        data.append(reader)
            
        
print(len(data[0]))

Input file daily_20241108T0927_000.csv has 615620 non-null elements.
Input file daily_20241108T0928_001.csv has 570158 non-null elements.
Input file daily_20241108T0931_002.csv has 648480 non-null elements.
Input file daily_20241108T0932_003.csv has 561924 non-null elements.
Input file daily_20241108T0933_004.csv has 608006 non-null elements.
Input file daily_20241108T0933_005.csv has 482439 non-null elements.
Input file daily_20241108T0934_006.csv has 523782 non-null elements.
Input file daily_20241108T0935_007.csv has 512855 non-null elements.
Input file daily_20241108T0936_008.csv has 539241 non-null elements.
Input file daily_20241108T0937_009.csv has 586794 non-null elements.
Input file daily_20241108T0938_010.csv has 547088 non-null elements.
Input file daily_20241108T0938_011.csv has 492207 non-null elements.
615620

In [46]:
# read our metadata file
meta_df = pd.read_csv("bc_station_metadata/metadata_20241115T0843.csv", dtype={'Station Number': 'str'}, low_memory=False)
# change header "Station Number" -> "Station ID"
meta_df.rename(columns={"Station Number":"Station ID"}, inplace=True)

In [47]:
meta_df['Station ID']

0       07EA001
1       07EA002
2       07EA004
3       07EA005
4       07EA006
         ...
2468    10CD003
2469    10CD004
2470    10CD005
2471    10CD006
2472    10DA001
Name: Station ID, Length: 2473, dtype: object

In [50]:
combined_data = pd.read_csv("combined_data.csv")
combined_data

,Unnamed: 0,Station ID,Date,Daily Discharge,SYM1,Daily Water Level,SYM2,Station Name,Province,Status,...,Regulation,Data Type,Operation Schedule,Sediment,RHBN,Real-Time,Datum Name,Publishing Office,Operating Agency,Contributed
0,0,07EA005,2011/01/01,60.20,B,1.075,NaN,FINLAY RIVER ABOVE AKIE RIVER,BC,Active,...,N,Flow and Level,Continuous,N,N,Y,ASSUMED DATUM,VANCOUVER,NaN,N
1,1,07EA005,2011/01/02,59.70,B,1.082,NaN,FINLAY RIVER ABOVE AKIE RIVER,BC,Active,...,N,Flow and Level,Continuous,N,N,Y,ASSUMED DATUM,VANCOUVER,NaN,N
2,2,07EA005,2011/01/03,59.20,B,1.098,NaN,FINLAY RIVER ABOVE AKIE RIVER,BC,Active,...,N,Flow and Level,Continuous,N,N,Y,ASSUMED DATUM,VANCOUVER,NaN,N
3,3,07EA005,2011/01/04,58.60,B,1.110,NaN,FINLAY RIVER ABOVE AKIE RIVER,BC,Active,...,N,Flow and Level,Continuous,N,N,Y,ASSUMED DATUM,VANCOUVER,NaN,N
4,4,07EA005,2011/01/05,58.10,B,1.109,NaN,FINLAY RIVER ABOVE AKIE RIVER,BC,Active,...,N,Flow and Level,Continuous,N,N,Y,ASSUMED DATUM,VANCOUVER,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048009,1048009,10DA001,2023/12/27,1.66,B,5.314,NaN,PETITOT RIVER BELOW HIGHWAY NO. 77,BC,Active,...,N,Flow and Level,Continuous,N,N,Y,ASSUMED DATUM,YELLOWKNIFE,NaN,N
1048010,1048010,10DA001,2023/12/28,1.64,B,5.324,NaN,PETITOT RIVER BELOW HIGHWAY NO. 77,BC,Active,...,N,Flow and Level,Continuous,N,N,Y,ASSUMED DATUM,YELLOWKNIFE,NaN,N
1048011,1048011,10DA001,2023/12/29,1.61,B,5.388,NaN,PETITOT RIVER BELOW HIGHWAY NO. 77,BC,Active,...,N,Flow and Level,Continuous,N,N,Y,ASSUMED DATUM,YELLOWKNIFE,NaN,N
1048012,1048012,10DA001,2023/12/30,1.59,B,5.456,NaN,PETITOT RIVER BELOW HIGHWAY NO. 77,BC,Active,...,N,Flow and Level,Continuous,N,N,Y,ASSUMED DATUM,YELLOWKNIFE,NaN,N
1048013,1048013,10DA001,2023/12/31,1.57,B,5.474,NaN,PETITOT RIVER BELOW HIGHWAY NO. 77,BC,Active,...,N,Flow and Level,Continuous,N,N,Y,ASSUMED DATUM,YELLOWKNIFE,NaN,N

In [142]:
combined_data = pd.read_csv("combined_data.csv")
combined_data['Date'] = pd.to_datetime(combined_data['Date'], format="%Y/%m/%d")#.dt.date

# do some manual filtering of stations with data over too small a period of time
combined_data = combined_data[combined_data['Station ID'] != '08GA026']
combined_data = combined_data[combined_data['Station ID'] != '08HE001']
combined_data = combined_data[combined_data['Station ID'] != '08LG070']
combined_data = combined_data[combined_data['Station ID'] != '08LF023']
combined_data = combined_data[combined_data['Station ID'] != '08KE018']
combined_data = combined_data[combined_data['Station ID'] != '08ND021']
combined_data = combined_data[combined_data['Station ID'] != '08MF035']
combined_data = combined_data[combined_data['Station ID'] != '08CE005']
combined_data = combined_data[combined_data['Station ID'] != '07ED001']
combined_data = combined_data[combined_data['Station ID'] != '08GD010']
combined_data = combined_data[combined_data['Station ID'] != '08MG028']
combined_data = combined_data[combined_data['Station ID'] != '08NK030']
combined_data = combined_data[combined_data['Station ID'] != '09AA006']
combined_data = combined_data[combined_data['Station ID'] != '08LF033']
combined_data = combined_data[combined_data['Station ID'] != '08HD035']
combined_data = combined_data[combined_data['Station ID'] != '08FA002']
combined_data = combined_data[combined_data['Station ID'] != '08MD013']
combined_data = combined_data[combined_data['Station ID'] != '08KH001']
combined_data = combined_data[combined_data['Station ID'] != '08PA012']
combined_data = combined_data[combined_data['Station ID'] != '08LD001']
combined_data = combined_data[combined_data['Station ID'] != '08EG012']
combined_data = combined_data[combined_data['Station ID'] != '08EG019']
combined_data = combined_data[combined_data['Station ID'] != '07FC003']
combined_data = combined_data[combined_data['Station ID'] != '08NP003']
combined_data = combined_data[combined_data['Station ID'] != '07FD019']
combined_data = combined_data[combined_data['Station ID'] != '08LF094']
combined_data = combined_data[combined_data['Station ID'] != '10CD004']
combined_data = combined_data[combined_data['Station ID'] != '08NM146']
combined_data = combined_data[combined_data['Station ID'] != '08KE024']
combined_data = combined_data[combined_data['Station ID'] != '08LG056']
combined_data = combined_data[combined_data['Station ID'] != '08KH019']
combined_data = combined_data[combined_data['Station ID'] != '08KA009']
combined_data = combined_data[combined_data['Station ID'] != '08KH010']
combined_data = combined_data[combined_data['Station ID'] != '10CD005']
combined_data = combined_data[combined_data['Station ID'] != '07FC001']
combined_data = combined_data[combined_data['Station ID'] != '08MF005']



minDate = combined_data['Date'].min()
maxDate = combined_data['Date'].max()
minStation = ""
maxStation = ""
for station in combined_data['Station ID'].unique():
    stationMin = combined_data[combined_data["Station ID"] == station]['Date'].min()
    stationMax = combined_data[combined_data["Station ID"] == station]['Date'].max()
    if stationMin > minDate:
        minDate = stationMin
        minStation = station
    if stationMax < maxDate:
        maxDate = stationMax
        maxStation = station

print(f'MinDate: {minDate}\nMaxDate: {maxDate}')
print(minStation, maxStation)

MinDate: 2013-01-01 00:00:00
MaxDate: 2023-12-31 00:00:00
10DA001

In [174]:
# TODO before pivot, get rid of some more useless columns

columns = ['Date','Station ID','Station Name','Province','Latitude','Longitude','Daily Discharge',
           'SYM1','Daily Water Level','SYM2']
combined_data = combined_data[columns]

In [175]:
pivot_df = combined_data.pivot(columns="Station ID", index="Date")

In [177]:
x = pd.date_range(start="1/1/2013", end="12/31/2023")

In [178]:
pivot_df = pivot_df.reindex(x)

In [202]:
pivot_df['Daily Water Level']

Station ID,07EA005,07EB002,07EC002,07EC003,07ED003,07FA004,07FA005,07FA006,07FB001,07FB002,...,08NN028,09AA013,09AE003,10BE007,10BE009,10CA001,10CB001,10CD001,10CD003,10DA001
2013-01-01,1.113,1.794,1.801,2.354,1.167,1.914,0.001,0.874,2.451,8.022,...,0.841,10.760,1.039,2.752,7.644,6.890,1.629,-0.029,0.202,5.773
2013-01-02,1.105,1.777,1.806,2.347,1.139,2.055,0.040,0.868,2.446,8.015,...,0.847,10.761,1.023,2.743,7.640,6.890,1.627,-0.035,0.196,5.781
2013-01-03,1.091,1.757,1.806,2.335,1.128,2.232,0.077,0.866,2.433,8.006,...,NaN,10.758,1.016,2.768,7.637,6.880,1.621,-0.037,0.180,5.782
2013-01-04,1.081,1.741,1.801,2.320,1.115,2.254,0.081,0.868,2.412,7.994,...,NaN,10.758,1.000,2.726,7.636,6.880,1.619,-0.042,0.177,5.783
2013-01-05,1.073,1.725,1.798,2.310,1.118,2.279,0.064,0.862,2.394,7.979,...,NaN,10.754,0.988,2.708,7.632,6.880,1.616,-0.044,0.176,5.785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-27,0.244,1.922,1.733,2.498,0.627,0.146,-0.212,0.294,2.574,7.906,...,0.792,10.888,0.914,2.091,7.549,6.518,1.520,-0.123,0.227,5.314
2023-12-28,0.253,1.913,1.731,2.484,0.605,0.144,-0.136,0.287,2.553,8.052,...,0.788,10.883,0.997,2.091,7.550,6.535,1.513,-0.139,0.224,5.324
2023-12-29,0.256,1.894,1.727,2.452,0.684,0.144,0.002,0.281,2.389,8.125,...,0.787,10.884,0.926,2.130,7.534,6.537,1.496,-0.081,0.221,5.388
2023-12-30,0.273,1.900,1.724,2.400,0.708,0.140,-0.062,0.268,2.349,8.132,...,0.787,10.887,0.910,2.151,7.556,6.530,1.525,-0.085,0.216,5.456
2023-12-31,0.265,1.885,1.725,2.370,0.765,0.133,-0.068,0.262,2.348,8.144,...,0.788,10.880,0.864,2.092,7.550,6.517,1.533,-0.104,0.212,5.474

In [ ]:
pivot_df['Daily Water Level'].dropna(axis=0, thresh=169)
# so if we allow some dates to miss data for up to 31 stations, then we can use this date range

Station ID,07EA005,07EB002,07EC002,07EC003,07ED003,07FA004,07FA005,07FA006,07FB001,07FB002,...,08NN028,09AA013,09AE003,10BE007,10BE009,10CA001,10CB001,10CD001,10CD003,10DA001
2013-01-01,1.113,1.794,1.801,2.354,1.167,1.914,0.001,0.874,2.451,8.022,...,0.841,10.760,1.039,2.752,7.644,6.890,1.629,-0.029,0.202,5.773
2013-01-02,1.105,1.777,1.806,2.347,1.139,2.055,0.040,0.868,2.446,8.015,...,0.847,10.761,1.023,2.743,7.640,6.890,1.627,-0.035,0.196,5.781
2013-01-03,1.091,1.757,1.806,2.335,1.128,2.232,0.077,0.866,2.433,8.006,...,NaN,10.758,1.016,2.768,7.637,6.880,1.621,-0.037,0.180,5.782
2013-01-04,1.081,1.741,1.801,2.320,1.115,2.254,0.081,0.868,2.412,7.994,...,NaN,10.758,1.000,2.726,7.636,6.880,1.619,-0.042,0.177,5.783
2013-01-05,1.073,1.725,1.798,2.310,1.118,2.279,0.064,0.862,2.394,7.979,...,NaN,10.754,0.988,2.708,7.632,6.880,1.616,-0.044,0.176,5.785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-27,0.244,1.922,1.733,2.498,0.627,0.146,-0.212,0.294,2.574,7.906,...,0.792,10.888,0.914,2.091,7.549,6.518,1.520,-0.123,0.227,5.314
2023-12-28,0.253,1.913,1.731,2.484,0.605,0.144,-0.136,0.287,2.553,8.052,...,0.788,10.883,0.997,2.091,7.550,6.535,1.513,-0.139,0.224,5.324
2023-12-29,0.256,1.894,1.727,2.452,0.684,0.144,0.002,0.281,2.389,8.125,...,0.787,10.884,0.926,2.130,7.534,6.537,1.496,-0.081,0.221,5.388
2023-12-30,0.273,1.900,1.724,2.400,0.708,0.140,-0.062,0.268,2.349,8.132,...,0.787,10.887,0.910,2.151,7.556,6.530,1.525,-0.085,0.216,5.456
2023-12-31,0.265,1.885,1.725,2.370,0.765,0.133,-0.068,0.262,2.348,8.144,...,0.788,10.880,0.864,2.092,7.550,6.517,1.533,-0.104,0.212,5.474